### ISSUE TITLE
Forced shutdown when submitting pilots to Stampede and Comet

### ISSUE THREAD

**Issue by Nikhil-Shenoy** [radical-cybertools/radical.ensemblemd#121]
```
2015-11-02 20:08:05,351: radical.pilot       : MainProcess                     : Thread-1       : ERROR   : pilot manager controller thread caught system exi
t -- forcing application shutdown
Traceback (most recent call last):
  File "/home/nrs76/envs/profiler_2/local/lib/python2.7/site-packages/radical/pilot/controller/pilot_manager_controller.py", line 335, in run
    self.call_callbacks(pilot_id, new_state)
  File "/home/nrs76/envs/profiler_2/local/lib/python2.7/site-packages/radical/pilot/controller/pilot_manager_controller.py", line 258, in call_callbacks
    cb(self._shared_data[pilot_id]['facade_object'](), new_state)
  File "/home/nrs76/envs/profiler_2/local/lib/python2.7/site-packages/radical/ensemblemd/single_cluster_environment.py", line 137, in pilot_state_cb
    sys.exit(0)
SystemExit: 0
```

**Comment by Nikhil-Shenoy** [comment]
Traceback (most recent call last):
  File "repex.py", line 289, in <module>
    cluster.deallocate()
  File "/home/nrs76/envs/profiler_2/local/lib/python2.7/site-packages/radical/ensemblemd/single_cluster_environment.py", line 103, in deallocate
    self._session.close(cleanup=self._cleanup)
  File "/home/nrs76/envs/profiler_2/local/lib/python2.7/site-packages/radical/pilot/session.py", line 281, in close
    pmgr.close (terminate=terminate)
  File "/home/nrs76/envs/profiler_2/local/lib/python2.7/site-packages/radical/pilot/pilot_manager.py", line 175, in close
    self.cancel_pilots()
  File "/home/nrs76/envs/profiler_2/local/lib/python2.7/site-packages/radical/pilot/pilot_manager.py", line 566, in cancel_pilots
    self._worker.register_cancel_pilots_request(pilot_ids=pilot_ids)
  File "/home/nrs76/envs/profiler_2/local/lib/python2.7/site-packages/radical/pilot/controller/pilot_manager_controller.py", line 601, in register_cancel_pil
ots_request
    time.sleep(0.3)

**Comment by Nikhil-Shenoy** [comment]
I tried to submit a variant on the example repex script, and I've been getting this error on both Stampede and Comet. The application does start running and generating output, but it never terminates and never generates the total output

**Comment by Nikhil-Shenoy** [comment]
Just tried to test this ticket again and got the same error. I cloned the EnMD repo and installed the devel branch, then ran the Getting Started script. I ran into the same issue where the script stalls on `time.sleep(0.3)` and I get a `pilot manager controller thread caught system exit -- forcing application shutdown` error. All of this was done on a fresh install with a new virtual environment.

**Comment by vivek-bala** [comment]
Could you run it again with RADICAL_PILOT_VERBOSE=debug and RADICAL_ENMD_VERBOSE=debug and paste the verbose output pls ?

**Comment by Nikhil-Shenoy** [comment]
I've attached the files that I used. `err.txt` contains the verbose output, and `simple.py` is the script.
[err.txt](https://github.com/radical-cybertools/radical.ensemblemd/files/87624/err.txt)
[simple.txt](https://github.com/radical-cybertools/radical.ensemblemd/files/87625/simple.txt)

**Comment by andre-merzky** [comment]
Ah: hello Unicode, my old friend....

```
2016-01-12 16:38:26,015: radical.pilot       : MainProcess                     : PilotLauncherWorker-1: DEBUG   : Copying sdist 'file://localhost/home/nrs76/envs/fresh/local/lib/python2.7/site-packages/radical/pilot/controller/..//radical.pilot-0.38.tar.gz' to sandbox (file://localhost/home/nrs76/radical.pilot.sandbox/rp.session.ip-10-184-31-85.nrs76.016812.0000-pilot.0000/).
Exception in thread PilotLauncherWorker-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/nrs76/envs/fresh/local/lib/python2.7/site-packages/radical/pilot/controller/pilot_launcher_worker.py", line 811, in run
    logger.exception ('\n'.join (log_messages))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 329: ordinal not in range(128)
```

Nikhil, what version/branch of RP are you using?

**Comment by Nikhil-Shenoy** [comment]
Hi Andre,

I'm using RP version 0.38. And didn't install RP separately from EnMD. I believe EnMD installs the master branch of RP by default, doesn't it?

**Comment by vivek-bala** [comment]
EnMD would install the released version of RP which is 0.38. I think the source of the error is different. This above unicode error simply can't print the original error (?).

**Comment by vivek-bala** [comment]
Also, could you confirm you have the rp tarball locally at ```/home/nrs76/envs/fresh/local/lib/python2.7/site-packages/radical/pilot/controller/..//radical.pilot-0.38.tar.gz``` ?

**Comment by Nikhil-Shenoy** [comment]
Is that path correct? Just wondering about the `../` in the middle.

**Comment by andre-merzky** [comment]
Yes, the path is correct.

Vivek: you are likely right about this error being a secondary one.  What I think is happening is this: During staging of the RP-0.38 tarball, and exception is raised.  The exception is caught, and RP attempts in line 811 (https://github.com/radical-cybertools/radical.pilot/blob/master/src/radical/pilot/controller/pilot_launcher_worker.py#L811) to log the exception.  But the string formatting operation (`'\n'.join(messages)`) stumbles over some unicode chars which is part of the caught error, probably bubbling up from the SAGA layer, so it barfs up before logging the actual error.

So there are two things to fix: (1) unicode handling on RP level (again), and (2) the actual error.

Nikhil, to see the actual error, would you mind also setting `SAGA_VERBOSE=DEBUG` and sending the output again?  Thanks!

For the unicode problem, I'll open an RP ticket (or update one I believe already exists).

**Comment by Nikhil-Shenoy** [comment]
I couldn't find the tar ball that you mentioned, Vivek. 

Andre, here's the output with `SAGA_VERBOSE=DEBUG`:
[saga_err.txt](https://github.com/radical-cybertools/radical.ensemblemd/files/89273/saga_err.txt)

**Comment by vivek-bala** [comment]
Thanks Nikhil. I think that is probably the source of the error. How did you install virtualenv ? ```pip install .``` or ```python setup.py install``` ?

**Comment by Nikhil-Shenoy** [comment]
I used `pip install ./` in the cloned repository.

**Comment by vivek-bala** [comment]
Hmmm, that should be fine. Wondering why the tarball doesn't exist. I think I've had this issue before, required some changes RU (correct me if I'm wrong Andre). But I can't reproduce this issue with the released version (stack).

**Comment by andre-merzky** [comment]
Yes, I agree, the tarball is missing is a problem.  And indeed, it should always get installed on `pip install .`.  Would you please try that again, but make sure that RP is uninstalled before?  Like:

```
pip uninstall -y radical.pilot
pip install .
```

or

```
pip install --upgrade .
```

Please check afterwards if that tarball exists.  FWIW, a similar tarball if expected to exist for radical.utils and saga-python...

**Comment by Nikhil-Shenoy** [comment]
After running it or just after installation?

**Comment by vivek-bala** [comment]
After executing the above commands (to uninstall and install/ upgrade), please check if you have the tarball in that same path as above.

**Comment by Nikhil-Shenoy** [comment]
No, I don't have it.

**Comment by vivek-bala** [comment]
Could you paste the installation log please ? (Please use gist or markdown)

**Comment by Nikhil-Shenoy** [comment]
Here's the gist: https://gist.github.com/Nikhil-Shenoy/8e5a700fa94d36187e23

**Comment by andre-merzky** [comment]
Could you please also add the commands you use?

Also:
* what python version do you use, and what pip version?
* how did you create the virtualenv?

Thanks!

**Comment by vivek-bala** [comment]
Do you have pip wheels installed ? When you create a virtualenv, you should get a message about it.

I think this is resolved in rp devel. Another way is to downgrade pip to 1.7.1.

**Comment by Nikhil-Shenoy** [comment]
This is what I do:

`virtualenv ~/envs/fresh --system-site-packages
source ~/envs/fresh/bin/activate
cd ~/radical.ensemblemd
pip uninstall -y radical.pilot
pip install ./
ls /home/nrs76/envs/fresh/local/lib/python2.7/site-packages/radical/pilot/controller/..//radical.pilot-0.38.tar.gz
`
My python version is 2.7.6

After doing all this, I still don't have the tar ball. I don't have anything after the `../controller` part of the path.

**Comment by andre-merzky** [comment]
So, after install there is nothing in `ls /home/nrs76/envs/fresh/local/lib/python2.7/site-packages/radical/pilot/`?  Where do the files end up?  You should be able to find out with:

```
python -c 'import radical.pilot as rp; print rp.__file__'
```

**Comment by Nikhil-Shenoy** [comment]
Sorry, I have the `controller` directory. In there, I have the following:

`__init__.py`
`pilot_launcher_worker.py`
`__init__.pyc`
`pilot_launcher_worker.pyc`
`input_file_transfer_worker.py`
`pilot_manager_controller.py`
`input_file_transfer_worker.pyc`
`pilot_manager_controller.pyc`
`output_file_transfer_worker.py`
`unit_manager_controller.py`
`output_file_transfer_worker.pyc`
`unit_manager_controller.pyc`

**Comment by vivek-bala** [comment]
Could you check the pip version as well ?

**Comment by Nikhil-Shenoy** [comment]
pip version is 7.1.2

**Comment by vivek-bala** [comment]
After source your (new)virtualenv, please do a ```pip install pip==1.4.1 --upgrade```. Then reinstall ensemblemd and try again.

**Comment by vivek-bala** [comment]
(You would get a longer installation log)

**Comment by Nikhil-Shenoy** [comment]
Vivek, here's the install log:

[new_enmd_install.txt](https://github.com/radical-cybertools/radical.ensemblemd/files/90758/new_enmd_install.txt)

**Comment by vivek-bala** [comment]
Seems like the usual installation log, did it work ?

**Comment by Nikhil-Shenoy** [comment]
No, I still don't see the tar ball.

**Comment by Nikhil-Shenoy** [comment]
Wait, I do find the tar ball now.

**Comment by vivek-bala** [comment]
I do see this error in the installation log:

```
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/zmq/backend/cython/utils.o -o build/lib.linux-x86_64-2.7/zmq/backend/cython/utils.so
      File "/home/nrs76/envs/new/lib/python2.7/site-packages/zmq/asyncio.py", line 79
        "{!r}".format(fileobj)) from None
                                   ^
    SyntaxError: invalid syntax
    
      File "/home/nrs76/envs/new/lib/python2.7/site-packages/zmq/tests/_test_asyncio.py", line 43
        yield from a.send(b'hi')
                 ^
    SyntaxError: invalid syntax
    
      File "/home/nrs76/envs/new/lib/python2.7/site-packages/zmq/auth/asyncio.py", line 28
        events = yield from self.__poller.poll()
                          ^
    SyntaxError: invalid syntax
    
    
    warning: no files found matching 'tox.ini'
    no previously-included directories found matching 'docs/build'
    no previously-included directories found matching 'docs/gh-pages'
    warning: no previously-included files found matching 'bundled/zeromq/src/Makefile*'
    warning: no previously-included files found matching 'setup.cfg'
    warning: no previously-included files found matching 'zmq/libzmq*'
    warning: no previously-included files matching '__pycache__/*' found anywhere in distribution
    warning: no previously-included files matching '.deps/*' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    warning: no previously-included files matching '*.pyd' found anywhere in distribution
    warning: no previously-included files matching '.git*' found anywhere in distribution
    warning: no previously-included files matching '.DS_Store' found anywhere in distribution
    warning: no previously-included files matching '.mailmap' found anywhere in distribution
    warning: no previously-included files matching 'Makefile.am' found anywhere in distribution
    warning: no previously-included files matching 'Makefile.in' found anywhere in distribution
  Running setup.py install for apache-libcloud
    
    no previously-included directories found matching 'libcloud/test/secrets.py'
  Running setup.py install for backports.ssl-match-hostname
    
Successfully installed radical.utils radical.pilot setuptools radical.ensemblemd colorama saga-python pymongo python-hostlist netifaces setproctitle ntplib pyzmq apache-libcloud backports.ssl-match-hostname
```

**Comment by Nikhil-Shenoy** [comment]
I also tried running the "getting started" again and got this:

`Exception in thread Thread-9 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
File "/home/nrs76/envs/new/local/lib/python2.7/site-packages/saga/adaptors/shell/shell_job.py", line in run
File "/home/nrs76/envs/new/local/lib/python2.7/site-packages/radical/utils/signatures.py", line 456, in signature_check
File "/home/nrs76/envs/new/local/lib/python2.7/site-packages/radical/utils/signatures.py", line 216, in check
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
Exception in thread Thread-8 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
File "/home/nrs76/envs/new/local/lib/python2.7/site-packages/saga/adaptors/shell/shell_job.py", line, in run
File "/home/nrs76/envs/new/local/lib/python2.7/site-packages/radical/utils/signatures.py", line 456, in signature_check
File "/home/nrs76/envs/new/local/lib/python2.7/site-packages/radical/utils/signatures.py", line 216, in check
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
`

**Comment by Nikhil-Shenoy** [comment]
I ran the "getting started" again and got this: 

https://gist.github.com/Nikhil-Shenoy/13412be8baea8315ecf1

**Comment by vivek-bala** [comment]
Is that at the end of the script ? Does the script execute ? Do you get the expected data ?

**Comment by Nikhil-Shenoy** [comment]
It seems like the data is being recorded correctly. I'm going to try again with my script and see what happens.

**Comment by vivek-bala** [comment]
Ok. The interpreter that you got is likely during pilot cancellation.

**Comment by andre-merzky** [comment]
That unicode-offending part of RP has been rewritten by now.
